### ISSUE TITLE
Using function to define entities 

### ISSUE THREAD

**Issue by atefBB** [data-client/rest-hooks#2455]
Thanks for the great package !
Is there a plan to support using `vanilla` functions to defien entities ? 
I wanna to understand why you choose classes to define entities ? It's seems simple -for me- to define an entity as `vanilla` function or just a `plain old object` !

**Comment by ntucker** [comment]
In one word: type-safety

In Javascript, using function or classes there isn't a huge difference in what they can do (outside of 'super' working). However, TypeScript makes defining types a lot easier with classes. Because of this the data types users define are done with classes. That doesn't mean much of the internals are not using function-first approach.

We just landed a PR to making [defining entities from existing classes](https://resthooks.io/rest/api/schema.Entity), which is maybe along the lines of what you were wanting. This still uses classes for the type safety but allows you to define the critical options like `key` as a function argument.

If something like `schema.Entity(Article)` is what you were interested, then please reply here and I'll get the new feature released today. Otherwise I was probably going to wait a day or two. If this isn't what you were wanting, I would love to hear more about the specifics of your use case and why classes aren't ideal. Perhaps with an example API you would prefer.

**Comment by ntucker** [comment]
Without further information I'll have to close this issue. Feel free to respond if you have more information!
